interface Content {
  type: String!
  text: String
  url: String
}

type Story {
  id: String!
  title: String!
  date: String
  description: String
  content: [Content]
}

type Goal {
  score: String!
  minute: Int
  goal: String
  assist: String
  situation: String
  standard: String
  origin: String
  type: String
  x: Int
  y: Int
}

type Match {
  date: String
  teams: [String]
  result: [Int]
  goals: [Goal]
}

type Query {
  stories: [Story]
  story(id: String!): Story
  matches: [Match]
  match(date: String!): Match
}

type Mutation {
  upsertStory(story: Story!): Story
  upsertMatch(match: Match!): Match
  publish: [Story]
}

schema {
  query: Query
  mutation: Mutation
}
