interface Content {
  type: String!
  text: String
  url: String
}

type Story {
  id: String!
  title: String!
  date: String
  description: String
  content: [Content]
}

type Match {
  date: String
  teams: [String]
}

type Query {
  stories: [Story]
  story(id: String!): Story
  matches: [Match]
}

type Mutation {
  upsertStory(story: Story!): Story
  publish: [Story]
}

schema {
  query: Query
  mutation: Mutation
}
